name: Emscripten CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache@v3
      id: cache-toolchaine
      with:
        path: |
          ~/emsdk
        key: ${{ runner.os }}-emscripten-latest-1

    - name: Install Emscripten SDK
      if: steps.cache-toolchaine.outputs.cache-hit != 'true'
      run: |
        cd ~/
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest

    - name: Emscripten build
      run: |
        source ~/emsdk/emsdk_env.sh
        mkdir build && cd build
        emcmake cmake ..
        emmake make

    - name: webpack build
      run: |
        npm install
        npm run webpack
